version: "2"
services:
  rancher-minio-driver:
    privileged: true
    image : fahim74/rancher-rexray-s3-plugin:minio
    network_mode: host
    cap_add:
      - SYS_ADMIN
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
      io.rancher.container.dns: 'true'
    environment:
      S3FS_ENTRY: "${S3FS_ENTRY}"
      S3FS_ACCESSKEY: "${S3FS_ACCESSKEY}"
      S3FS_SECRETKEY: "${S3FS_SECRETKEY}"
    volumes:
      - /run:/run
      - /var/run:/var/run
      - /dev:/host/dev
      - /var/lib/rancher/volumes:/var/lib/rexray/volumes:shared