.catalog:
  name: "Rancher Minio Storage Driver"
  version: 0.3.0
  description: |
    Docker volume plugin for Minio
  questions:
    - variable: S3FS_ENTRY
      label: S3 Endpoint
      type: string
      description: The S3 endpoint to use
      required: true
    - variable: S3FS_ACCESSKEY
      label: S3 Access Key
      type: password
      description: S3 Access Key
      required: true
    - variable: S3FS_SECRETKEY
      label: S3 Secret Key
      type: password
      description: S3 Access Key
      required: true

rancher-minio-driver:
  storage_driver:
    name: rancher-s3
    scope: environment
    volume_access_mode: multiHostRW