.catalog:
  name: "Rancher Minio Storage Driver"
  version: 0.3.0
  description: |
    Docker volume plugin for Minio
  questions:
    - variable: S3FS_ACCESSKEY
      label: S3 Access Key
      type: password
      description: S3 Access Key
      required: true
    - variable: S3FS_SECRETKEY
      label: S3 Secret Key
      type: password
      description: S3 Access Key
      required: true

rexray-s3-driver:
  storage_driver:
    name: rexray
    scope: environment
    volume_access_mode: multiHostRW