version: "2"
services:
  rancher-s3-driver:
    privileged: true
    image : fahim74/rancher-rexray-s3-plugin
    network_mode: host
    cap_add:
      - SYS_ADMIN
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
      io.rancher.container.dns: 'true'
    environment:
      S3FS_ENTRY: "${S3FS_ENTRY}"
      S3FS_ACCESSKEY: "${S3FS_ACCESSKEY}"
      S3FS_SECRETKEY: "${S3FS_SECRETKEY}"
      S3FS_OPTIONS: "${S3FS_OPTIONS}"
    volumes:
      - /run:/run:shared
      - /var/run:/var/run:shared
      - /dev:/host/dev:shared
      - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
      - /var/run/docker.sock:/var/run/docker.sock