version: '2'
services:
  s3fs-driver:
    privileged: true
    network_mode: host
    image: dahendel/storage-s3fs
    pid: host
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
      io.rancher.container.dns: 'true'
    environment:
      S3FS_ENDPOINT: '${S3FS_ENDPOINT}'
      S3FS_ACCESSKEY: '${S3FS_ACCESSKEY}'
      S3FS_SECRETKEY: '${S3FS_SECRETKEY}'
      S3FS_OPTIONS: '${S3FS_OPTIONS}'
      LIBSTORAGE_VOLUME_OPERATIONS_MOUNT_ROOT_PATH: '${MOUNT_ROOT_PATH}'
    volumes:
    - /run:/run
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes